on: [ push, pull_request ]
name: Build and Publish
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: ianwalter/puppeteer@master
      with:
        entrypoint: npm
        args: install
    - name: Test
      uses: ianwalter/puppeteer@master
      with:
        entrypoint: npm
        args: test
  publish:  
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/bent'
    steps:
    - name: Publish
      uses: mikeal/merge-release@master
      if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/bent'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - uses: mikeal/bundle-size-action@master
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
